name: Build & Push cmake_conan container

on:
  push:
    branches: [ main ]
    paths:
      - "cmake_conan/**"
      - ".github/workflows/cmake_with_conan_workflow.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "cmake_conan/**"
      - ".github/workflows/cmake_with_conan_workflow.yml"
  workflow_dispatch:

env:
  CONAN_VERSION: 2.0.6
  CMAKE_VERSION: 3.26.4
  LATEST_VERSION: 12

jobs:
  build_tag_push_containers:
    strategy:
      fail-fast: false
      matrix:
        gcc_version: [10, 11, 12]
        repository: ["docker.io/loiclopez/cmake_conan", "ghcr.io/loic-lopez/cmake_conan"]
    defaults:
      run:
        working-directory: cmake_conan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add prefix to semVer calculated by GitVersion
        id: prefixed_semver
        run: echo 'semVer=gcc_${{ matrix.gcc_version }}-cmake_${{ env.CMAKE_VERSION }}-conan_${{ env.CONAN_VERSION }}' >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: contains(matrix.repository, 'docker.io')
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        if: contains(matrix.repository, 'ghcr.io')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PUSH_CR_PAT }}

      - name: Create list of tags
        #if: contains(needs.build.outputs.branchName, 'main') &&
        id: compute_tags
        shell: bash
        run: |
          tags="${{ matrix.repository }}:${{ steps.prefixed_semver.outputs.semVer }}"
          if [[ "${{ matrix.gcc_version }}" == "${{ env.LATEST_VERSION }}" ]]; then
            tags="${tags},${{ matrix.repository }}:latest"
          fi
          echo "tags=${tags}" >> $GITHUB_OUTPUT

      - name: Build and push ${{ matrix.repository }}
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.compute_tags.outputs.tags }}
          build-args: | 
            GCC_VERSION=${{ matrix.gcc_version }} 
            CMAKE_VERSION=${{ env.CMAKE_VERSION }} 
            CONAN_VERSION=${{ env.CONAN_VERSION }}
